# Generated by Django 4.1 on 2022-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr1', models.CharField(max_length=100)),
                ('ingr2', models.CharField(max_length=50)),
                ('ingr3', models.CharField(max_length=50)),
                ('ingr4', models.CharField(max_length=50)),
            ],
        ),
    ]
