# Generated by Django 4.1 on 2022-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsuggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsuggestion',
            name='price_range',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
