# Generated by Django 4.1 on 2022-09-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsuggestion', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsuggestion',
            name='img',
            field=models.ImageField(default=0, upload_to='picsfood'),
            preserve_default=False,
        ),
    ]
