# Generated by Django 4.1 on 2022-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsuggestion', '0004_foodsuggestion_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodsuggestion',
            old_name='ingr1',
            new_name='Dish_Name',
        ),
        migrations.RenameField(
            model_name='foodsuggestion',
            old_name='ingr2',
            new_name='ingredient2',
        ),
        migrations.RenameField(
            model_name='foodsuggestion',
            old_name='ingr3',
            new_name='ingredient3',
        ),
        migrations.RenameField(
            model_name='foodsuggestion',
            old_name='ingr4',
            new_name='ingredient4',
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
